name: fuzzle
description: "Focused study app with sessions, logs, Bluetooth pairing, and desktop UX."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  go_router: ^13.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  window_manager: ^0.3.7
  flutter_blue_plus: ^1.32.12
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add assets here
  assets:
    - lib/static/